amaranth-lang/rfcs

text/0000-remove-const-normalize.md

[Rendered](https://github.com/amaranth-lang/rfcs/blob/remove-const-normalize/text/0000-remove-const-normalize.md)

Remove `Const.normalize`

---

text/0000-const-castable-exprs.md

[Rendered](https://github.com/amaranth-lang/rfcs/blob/const-castable/text/0000-const-castable-exprs.md)

Const-castable expressions

---

text/0004-const-castable-exprs.md

The described behavior is unfortunately not possible to implement without RFC #7. The amended behavior is a subset of the previous one and so it is mostly backwards compatible (where the precise type of the value returned is not depended on).

RFC #4: amend behavior of enumerations with const-castable members

---

text/0009-const-init-shape-castable.md

It serves no purpose other than to complicate `Const.cast`'s type signature, and introduces an edge case of `shape` being a `Shape` and not a `ShapeCastable`, for which no behavior seems correct.

RFC #9: remove pointless `Const.cast(obj, shape)` overload

---

text/0006-stdlib-crc.md

See https://github.com/amaranth-lang/amaranth/pull/681 for implementation.
[Rendered](https://github.com/adamgreig/amaranth-rfcs/blob/crc/text/0006-stdlib-crc.md).

CRC generator

---

text/0000-deprecate-non-fwft-fifos.md

[Rendered](https://github.com/whitequark/amaranth-rfcs/blob/deprecate-non-fwft-fifos/text/0000-deprecate-non-fwft-fifos.md)

Add an RFC for deprecating non-FWFT FIFOs

---

text/0002-interfaces.md

This function isn't easy to implement with the existing API and is quite useful when connecting `lib.wiring` based interfaces to the outside world or components in other HDLs.

Amend RFC #2 to add `Signature.flatten`

---

text/0031-enumeration-type-safety.md

Rendered: https://github.com/wanda-phi/rfcs/blob/enum-type-safety/text/0031-enumeration-type-safety.md
Original issue: amaranth-lang/amaranth#778

Add an RFC for enumeration type safety.

---

text/0034-interface-rename.md

Rendered: https://github.com/wanda-phi/rfcs/blob/interface-rename/text/0034-interface-rename.md

Add an RFC for `amaranth.lib.wiring.Interface` renaming.

---

text/0039-empty-case.md

Rendered: https://github.com/wanda-phi/rfcs/blob/empty-case/text/0039-empty-case.md
Original issue: amaranth-lang/amaranth#1003

Add RFC for no-argument `m.Case()` semantic change.

---

text/0000-remove-log2-int.md
text/0017-remove-log2-int.md

[Rendered](https://github.com/jfng/amaranth-rfcs/blob/remove-log2-int/text/0017-remove-log2-int.md).

RFC: remove the `log2_int(n, need_pow2=True)` function.

---

text/0040-arbitrary-memory-shape.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/arbitrary-memory-shape/text/0040-arbitrary-memory-shape.md)

Add an RFC for arbitrary `Memory` shapes.

---

text/0046-shape-range-1.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/shape-range-1/text/0046-shape-range-1.md)
Implementation PR: amaranth-lang/amaranth#1077.

Add RFC for `Shape.cast(range(1))` change.

---

text/0040-arbitrary-memory-shape.md
text/0045-lib-memory.md

[Rendered](https://github.com/whitequark/amaranth-rfcs/blob/lib-memory/text/0000-lib-memory.md)

Move `hdl.memory` to `lib.memory` and extend it

---

text/0042-const-from-shape-castable.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/const-from-shape-castable/text/0042-const-from-shape-castable.md)

Add an RFC for `Const` from shape-castable.

---

text/0043-rename-reset-to-init.md

[Rendered](https://github.com/whitequark/amaranth-rfcs/blob/rename-reset/text/0000-rename-reset-to-init.md)

Rename `reset=` to `init=`

---

text/0050-print.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/print/text/0050-print.md)

Add an RFC for `Print` statement and string formatting.

---

text/0051-from-bits-literalview.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/literal/text/0051-from-bits-literalview.md)

Add an RFC for `ShapeCastable.from_bits` and `lib.data.Const`.

---

text/0053-ioport.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/ioport/text/0053-ioport.md)

RFC 53: Low-level I/O primitives.

---

text/0056-mem-wide.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/mem-wide/text/0056-mem-wide.md)

RFC 56: Asymmetric memory port width.

---

text/0054-read-port-init.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/read-port-init/text/0054-read-port-init.md)

RFC 54: Initial and reset values on memory read ports.

---

text/0036-async-testbench-functions.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/async-testbench-functions/text/0036-async-testbench-functions.md)

Add an RFC for async testbench functions.

---

text/0062-memory-data.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/mem-data/text/0062-memory-data.md)

RFC 62: The `MemoryData` class.

---

text/0059-no-domain-upwards-propagation.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/domain-prop/text/0059-no-domain-upwards-propagation.md)

Add an RFC for removing upwards propagation of clock domains

---

text/0058-valuecastable-format.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/valuecastable-format/text/0058-valuecastable-format.md)

Add an RFC for `ValueCastable` formatting.

---

text/0063-remove-lib-coding.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/remove-lib-coding/text/0063-remove-lib-coding.md)

Add an RFC for `lib.coding` removal.

---

text/0036-async-testbench-functions.md

[Rendered](https://github.com/whitequark/amaranth-rfcs/blob/rfc-36-update/text/0036-async-testbench-functions.md)

Amend RFC #36 with a concrete concurrency model

---

text/0052-choice.md

[Rendered](https://github.com/wanda-phi/rfcs/blob/choice/text/0052-choice.md)

Add RFC for `Choice`.

---

text/0069-simulation-port.md

[Rendered](https://github.com/whitequark/amaranth-rfcs/blob/simulation-port/text/0069-simulation-port.md)

Add RFC for introducing simulation ports

---

text/0066-simulation-time.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/simulation-time/text/0066-simulation-time.md).

RFC #66: Simulation time

---

text/0077-stream-port-name-conventions.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/stream-port-name-conventions/text/0077-stream-port-name-conventions.md).

RFC #77: Stream port name conventions.

---

text/0080-simulation-task-groups.md

[Rendered](https://github.com/zyp/amaranth-rfcs/blob/simulation-task-groups/text/0080-simulation-task-groups.md).

RFC #80: Simulation task groups.
